version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    restart: always
    ports:
      - "5432:5432"

  fast-api:
    build:
      context: ./app
    container_name: fast-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data: